name: cylonix 
description: Cross platform client app for cylonix services

# Make sure the version code (the number behind the '+') is higher than the
# previous version. Android requires the version code to be always higher
# when updating the app.
version: 1.0.8+37

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0'

dependencies:
  charset_converter: ^2.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.5.0
  downloadsfolder: ^1.2.0
  event_bus: ^2.0.0
  file_picker: ^8.1.7
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_logger:
    path: "plugins/flutter_logger"
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  introduction_screen: ^3.1.17
  json_annotation: ^4.8.1
  logger: ^2.5.0
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.0.2
  pull_down_button: ^0.10.2
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^7.0.1
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.0
  uuid: ^3.0.5
  ffi: ^2.1.4
  win32: ^5.14.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"
  flutter_lints: ^1.0.0
  freezed: ^2.5.8
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: false
  ios: false
  remove_alpha_ios: true
  image_path: "lib/assets/images/cylonix_1024.png"
  web:
    generate: false
    image_path: "lib/assets/images/cylonix_1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: false
    image_path: "lib/assets/images/cylonix_1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/images/cylonix_macos_512x512.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  #assets: #assets:
  #- assets/images/logo.png
  #- assets/images/map-pattern.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - .env.local
    - lib/assets/images/cylonix_128.png
    - lib/assets/images/cylonix_512.png
